- VSR: '2.9.0'
  vdrive: '52.0.13'
  reecu: '8.1.1'
  vehicle_sec: '3.2.0'
  telestation_sec: '1.15.0'
  depb: '2.3.0'
- VSR: '2.10.2'
  vdrive: '53.0.5'
  reecu: '8.1.2'
  vehicle_sec: '3.2.0'
  telestation_sec: '1.15.0'
  depb: '2.3.0'
